# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - api-teste-houer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test (API)
        run: |
          cd backend
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job (API)
        uses: actions/upload-artifact@v4
        with:
          name: node-api
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job (API)
        uses: actions/download-artifact@v4
        with:
          name: node-api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA41AB9FCC1D4579BA949C7DD4C9F3D2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DDA778E2F04043BA9DFABDAA81B7D084 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5F2FDD93449B4CFFBC651452F55C321A }}

      - name: 'Deploy to Azure Web App (API)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-teste-houer'
          slot-name: 'Production'
          package: ./
