# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - teste-crud-houer (Frontend)

on:
  workflow_run:
    workflows: ["Build and deploy Node.js app to Azure Web App - api-teste-houer"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set API URL env for production build
        run: echo "REACT_APP_API_URL=https://api-teste-houer.azurewebsites.net/" > .env
        working-directory: frontend

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build

      - name: Prepare artifact for deployment
        run: |
          cp -r frontend/build ./deploy
          cp frontend/package.json ./deploy/
          cp frontend/package-lock.json ./deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-frontend
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-frontend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7B512B411CB4EB4AB5E3733F382DD2E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C9883DCE058A468A80F175DC7A669075 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E7A4B791F41246A98E67353077B5CB80 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'teste-crud-houer'
          slot-name: 'Production'
          package: .

